export const calismaAlanlariData = {
  title: "Kişiye Özel Çalışma Alanları",
  category: "Ofis & Ev Ofis Mobilyaları",
  coverImage: "https://images.unsplash.com/photo-1611242331396-9b3035c601da?q=80&w=1974&auto=format&fit=crop",
  galleryDescription: "Verimliliğinizi ve konforunuzu artıracak, ergonomik ve şık çalışma masaları, kitaplıklar ve ofis mobilyaları tasarlıyoruz.",
  sections: [
    {
      id: 'ev-ofis',
      title: 'Ev Ofis Çözümleri',
      images: [
        { src: 'https://images.unsplash.com/photo-1611242331396-9b3035c601da?q=80&w=1974&auto=format&fit=crop', alt: 'Duvara entegre edilmiş, raflı ve modern ev ofis çalışma alanı', ref: 'CA-EO-01' },
        { src: 'https://images.unsplash.com/photo-1554224155-8d044b40a257?q=80&w=2070&auto=format&fit=crop', alt: 'Kişiye özel tasarlanmış, ahşap çalışma masası ve dolaplar', ref: 'CA-EO-02' },
        { src: 'https://images.unsplash.com/photo-1618220530752-a12fbf00057b?q=80&w=2000&auto=format&fit=crop', alt: 'Minimalist ve şık bir evdeki çalışma köşesi', ref: 'CA-EO-03' },
        { src: 'https://images.unsplash.com/photo-1603993041304-10a1f4f6e453?q=80&w=1974&auto=format&fit=crop', alt: 'Kitaplık ve depolama çözümleriyle zenginleştirilmiş çalışma odası', ref: 'CA-EO-04' },
        { src: 'https://images.unsplash.com/photo-1531403009530-b3a62309a8a7?q=80&w=1964&auto=format&fit=crop', alt: 'Sade ve fonksiyonel, duvara monte çalışma masası çözümü', ref: 'CA-EO-05' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+6', alt: 'Ev Ofis Çözümü Örnek 6', ref: 'CA-EO-06' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+7', alt: 'Ev Ofis Çözümü Örnek 7', ref: 'CA-EO-07' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+8', alt: 'Ev Ofis Çözümü Örnek 8', ref: 'CA-EO-08' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+9', alt: 'Ev Ofis Çözümü Örnek 9', ref: 'CA-EO-09' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+10', alt: 'Ev Ofis Çözümü Örnek 10', ref: 'CA-EO-10' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+11', alt: 'Ev Ofis Çözümü Örnek 11', ref: 'CA-EO-11' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+12', alt: 'Ev Ofis Çözümü Örnek 12', ref: 'CA-EO-12' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+13', alt: 'Ev Ofis Çözümü Örnek 13', ref: 'CA-EO-13' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+14', alt: 'Ev Ofis Çözümü Örnek 14', ref: 'CA-EO-14' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+15', alt: 'Ev Ofis Çözümü Örnek 15', ref: 'CA-EO-15' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+16', alt: 'Ev Ofis Çözümü Örnek 16', ref: 'CA-EO-16' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+17', alt: 'Ev Ofis Çözümü Örnek 17', ref: 'CA-EO-17' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+18', alt: 'Ev Ofis Çözümü Örnek 18', ref: 'CA-EO-18' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+19', alt: 'Ev Ofis Çözümü Örnek 19', ref: 'CA-EO-19' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+20', alt: 'Ev Ofis Çözümü Örnek 20', ref: 'CA-EO-20' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+21', alt: 'Ev Ofis Çözümü Örnek 21', ref: 'CA-EO-21' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+22', alt: 'Ev Ofis Çözümü Örnek 22', ref: 'CA-EO-22' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+23', alt: 'Ev Ofis Çözümü Örnek 23', ref: 'CA-EO-23' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+24', alt: 'Ev Ofis Çözümü Örnek 24', ref: 'CA-EO-24' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+25', alt: 'Ev Ofis Çözümü Örnek 25', ref: 'CA-EO-25' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+26', alt: 'Ev Ofis Çözümü Örnek 26', ref: 'CA-EO-26' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+27', alt: 'Ev Ofis Çözümü Örnek 27', ref: 'CA-EO-27' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+28', alt: 'Ev Ofis Çözümü Örnek 28', ref: 'CA-EO-28' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+29', alt: 'Ev Ofis Çözümü Örnek 29', ref: 'CA-EO-29' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+30', alt: 'Ev Ofis Çözümü Örnek 30', ref: 'CA-EO-30' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+31', alt: 'Ev Ofis Çözümü Örnek 31', ref: 'CA-EO-31' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+32', alt: 'Ev Ofis Çözümü Örnek 32', ref: 'CA-EO-32' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+33', alt: 'Ev Ofis Çözümü Örnek 33', ref: 'CA-EO-33' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+34', alt: 'Ev Ofis Çözümü Örnek 34', ref: 'CA-EO-34' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+35', alt: 'Ev Ofis Çözümü Örnek 35', ref: 'CA-EO-35' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+36', alt: 'Ev Ofis Çözümü Örnek 36', ref: 'CA-EO-36' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+37', alt: 'Ev Ofis Çözümü Örnek 37', ref: 'CA-EO-37' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+38', alt: 'Ev Ofis Çözümü Örnek 38', ref: 'CA-EO-38' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+39', alt: 'Ev Ofis Çözümü Örnek 39', ref: 'CA-EO-39' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ev+Ofis+40', alt: 'Ev Ofis Çözümü Örnek 40', ref: 'CA-EO-40' },
      ]
    },
    {
      id: 'profesyonel-ofisler',
      title: 'Profesyonel Ofisler',
      images: [
        { src: 'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=2070&auto=format&fit=crop', alt: 'Modern ve aydınlık, geniş pencereli ofis ortamı', ref: 'CA-PO-01' },
        { src: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop', alt: 'İşbirliğine dayalı, modern bir açık ofis alanı', ref: 'CA-PO-02' },
        { src: 'https://images.unsplash.com/photo-1517457373958-7ceba5d5f2f0?q=80&w=2070&auto=format&fit=crop', alt: 'Toplantı masası ve sandalyelerle donatılmış profesyonel ofis alanı', ref: 'CA-PO-03' },
        { src: 'https://images.unsplash.com/photo-1590479773265-7ebd2e69b763?q=80&w=2070&auto=format&fit=crop', alt: 'Ergonomik sandalye ve ayarlanabilir masa ile sağlıklı çalışma alanı', ref: 'CA-PO-04' },
        { src: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop', alt: 'Yaratıcı bir ekip için tasarlanmış, dinamik ofis ortamı', ref: 'CA-PO-05' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+6', alt: 'Profesyonel Ofis Örnek 6', ref: 'CA-PO-06' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+7', alt: 'Profesyonel Ofis Örnek 7', ref: 'CA-PO-07' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+8', alt: 'Profesyonel Ofis Örnek 8', ref: 'CA-PO-08' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+9', alt: 'Profesyonel Ofis Örnek 9', ref: 'CA-PO-09' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+10', alt: 'Profesyonel Ofis Örnek 10', ref: 'CA-PO-10' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+11', alt: 'Profesyonel Ofis Örnek 11', ref: 'CA-PO-11' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+12', alt: 'Profesyonel Ofis Örnek 12', ref: 'CA-PO-12' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+13', alt: 'Profesyonel Ofis Örnek 13', ref: 'CA-PO-13' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+14', alt: 'Profesyonel Ofis Örnek 14', ref: 'CA-PO-14' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+15', alt: 'Profesyonel Ofis Örnek 15', ref: 'CA-PO-15' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+16', alt: 'Profesyonel Ofis Örnek 16', ref: 'CA-PO-16' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+17', alt: 'Profesyonel Ofis Örnek 17', ref: 'CA-PO-17' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+18', alt: 'Profesyonel Ofis Örnek 18', ref: 'CA-PO-18' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+19', alt: 'Profesyonel Ofis Örnek 19', ref: 'CA-PO-19' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+20', alt: 'Profesyonel Ofis Örnek 20', ref: 'CA-PO-20' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+21', alt: 'Profesyonel Ofis Örnek 21', ref: 'CA-PO-21' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+22', alt: 'Profesyonel Ofis Örnek 22', ref: 'CA-PO-22' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+23', alt: 'Profesyonel Ofis Örnek 23', ref: 'CA-PO-23' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+24', alt: 'Profesyonel Ofis Örnek 24', ref: 'CA-PO-24' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+25', alt: 'Profesyonel Ofis Örnek 25', ref: 'CA-PO-25' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+26', alt: 'Profesyonel Ofis Örnek 26', ref: 'CA-PO-26' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+27', alt: 'Profesyonel Ofis Örnek 27', ref: 'CA-PO-27' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+28', alt: 'Profesyonel Ofis Örnek 28', ref: 'CA-PO-28' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+29', alt: 'Profesyonel Ofis Örnek 29', ref: 'CA-PO-29' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+30', alt: 'Profesyonel Ofis Örnek 30', ref: 'CA-PO-30' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+31', alt: 'Profesyonel Ofis Örnek 31', ref: 'CA-PO-31' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+32', alt: 'Profesyonel Ofis Örnek 32', ref: 'CA-PO-32' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+33', alt: 'Profesyonel Ofis Örnek 33', ref: 'CA-PO-33' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+34', alt: 'Profesyonel Ofis Örnek 34', ref: 'CA-PO-34' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+35', alt: 'Profesyonel Ofis Örnek 35', ref: 'CA-PO-35' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+36', alt: 'Profesyonel Ofis Örnek 36', ref: 'CA-PO-36' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+37', alt: 'Profesyonel Ofis Örnek 37', ref: 'CA-PO-37' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+38', alt: 'Profesyonel Ofis Örnek 38', ref: 'CA-PO-38' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+39', alt: 'Profesyonel Ofis Örnek 39', ref: 'CA-PO-39' },
        { src: 'https://via.placeholder.com/800x600.png?text=Profesyonel+Ofis+40', alt: 'Profesyonel Ofis Örnek 40', ref: 'CA-PO-40' },
      ]
    }
  ]
};