export const ticariMekanlarData = {
  title: "Ticari Mekan Çözümleri",
  category: "Profesyonel & Teknik Çözümler",
  coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2047&auto=format&fit=crop",
  galleryDescription: "Markanızın kimliğini yansıtan, estetik ve fonksiyonel ticari mekanlar tasarlıyoruz. Kafe, restoran, ofis ve mağaza projelerinizde anahtar teslim çözümler sunuyoruz.",
  sections: [
    {
      id: 'kafe-restoran',
      title: 'Kafe & Restoran',
      images: [
        { src: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=2047&auto=format&fit=crop', alt: 'Endüstriyel tarzda tasarlanmış, özel üretim bar ve masalara sahip bir kafe', ref: 'TM-KR-01' },
        { src: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2070&auto=format&fit=crop', alt: 'Şık bir restoranda kullanılan, özel tasarım ahşap masalar ve sandalyeler', ref: 'TM-KR-02' },
        { src: 'https://images.unsplash.com/photo-1510076857177-7470076d4098?q=80&w=2072&auto=format&fit=crop', alt: 'Bar ve lounge alanı için özel tasarlanmış, aydınlatmalı raf sistemleri', ref: 'TM-KR-03' },
        { src: 'https://images.unsplash.com/photo-1533777857889-45b709accb44?q=80&w=2070&auto=format&fit=crop', alt: 'Sıcak ve davetkar bir atmosfer yaratan, restoran için özel yapım ahşap paneller', ref: 'TM-KR-04' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+5', alt: 'Kafe & Restoran Örnek 5', ref: 'TM-KR-05' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+6', alt: 'Kafe & Restoran Örnek 6', ref: 'TM-KR-06' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+7', alt: 'Kafe & Restoran Örnek 7', ref: 'TM-KR-07' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+8', alt: 'Kafe & Restoran Örnek 8', ref: 'TM-KR-08' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+9', alt: 'Kafe & Restoran Örnek 9', ref: 'TM-KR-09' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+10', alt: 'Kafe & Restoran Örnek 10', ref: 'TM-KR-10' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+11', alt: 'Kafe & Restoran Örnek 11', ref: 'TM-KR-11' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+12', alt: 'Kafe & Restoran Örnek 12', ref: 'TM-KR-12' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+13', alt: 'Kafe & Restoran Örnek 13', ref: 'TM-KR-13' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+14', alt: 'Kafe & Restoran Örnek 14', ref: 'TM-KR-14' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+15', alt: 'Kafe & Restoran Örnek 15', ref: 'TM-KR-15' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+16', alt: 'Kafe & Restoran Örnek 16', ref: 'TM-KR-16' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+17', alt: 'Kafe & Restoran Örnek 17', ref: 'TM-KR-17' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+18', alt: 'Kafe & Restoran Örnek 18', ref: 'TM-KR-18' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+19', alt: 'Kafe & Restoran Örnek 19', ref: 'TM-KR-19' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+20', alt: 'Kafe & Restoran Örnek 20', ref: 'TM-KR-20' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+21', alt: 'Kafe & Restoran Örnek 21', ref: 'TM-KR-21' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+22', alt: 'Kafe & Restoran Örnek 22', ref: 'TM-KR-22' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+23', alt: 'Kafe & Restoran Örnek 23', ref: 'TM-KR-23' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+24', alt: 'Kafe & Restoran Örnek 24', ref: 'TM-KR-24' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+25', alt: 'Kafe & Restoran Örnek 25', ref: 'TM-KR-25' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+26', alt: 'Kafe & Restoran Örnek 26', ref: 'TM-KR-26' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+27', alt: 'Kafe & Restoran Örnek 27', ref: 'TM-KR-27' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+28', alt: 'Kafe & Restoran Örnek 28', ref: 'TM-KR-28' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+29', alt: 'Kafe & Restoran Örnek 29', ref: 'TM-KR-29' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+30', alt: 'Kafe & Restoran Örnek 30', ref: 'TM-KR-30' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+31', alt: 'Kafe & Restoran Örnek 31', ref: 'TM-KR-31' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+32', alt: 'Kafe & Restoran Örnek 32', ref: 'TM-KR-32' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+33', alt: 'Kafe & Restoran Örnek 33', ref: 'TM-KR-33' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+34', alt: 'Kafe & Restoran Örnek 34', ref: 'TM-KR-34' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+35', alt: 'Kafe & Restoran Örnek 35', ref: 'TM-KR-35' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+36', alt: 'Kafe & Restoran Örnek 36', ref: 'TM-KR-36' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+37', alt: 'Kafe & Restoran Örnek 37', ref: 'TM-KR-37' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+38', alt: 'Kafe & Restoran Örnek 38', ref: 'TM-KR-38' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+39', alt: 'Kafe & Restoran Örnek 39', ref: 'TM-KR-39' },
        { src: 'https://via.placeholder.com/800x600.png?text=Kafe+Restoran+40', alt: 'Kafe & Restoran Örnek 40', ref: 'TM-KR-40' },
      ]
    },
    {
      id: 'ofis-calisma-alanlari',
      title: 'Ofis & Çalışma Alanları',
      images: [
        { src: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop', alt: 'Modern ve açık planlı, ahşap detaylarla sıcaklık katılmış bir ofis alanı', ref: 'TM-OCA-01' },
        { src: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=2069&auto=format&fit=crop', alt: 'Toplantı odası için tasarlanmış büyük, masif ahşap masa ve teknolojik entegrasyonlar', ref: 'TM-OCA-02' },
        { src: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop', alt: 'Ofis ortak alanında yer alan, çalışanların dinlenmesi için tasarlanmış özel oturma alanı', ref: 'TM-OCA-03' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+4', alt: 'Ofis & Çalışma Alanı Örnek 4', ref: 'TM-OCA-04' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+5', alt: 'Ofis & Çalışma Alanı Örnek 5', ref: 'TM-OCA-05' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+6', alt: 'Ofis & Çalışma Alanı Örnek 6', ref: 'TM-OCA-06' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+7', alt: 'Ofis & Çalışma Alanı Örnek 7', ref: 'TM-OCA-07' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+8', alt: 'Ofis & Çalışma Alanı Örnek 8', ref: 'TM-OCA-08' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+9', alt: 'Ofis & Çalışma Alanı Örnek 9', ref: 'TM-OCA-09' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+10', alt: 'Ofis & Çalışma Alanı Örnek 10', ref: 'TM-OCA-10' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+11', alt: 'Ofis & Çalışma Alanı Örnek 11', ref: 'TM-OCA-11' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+12', alt: 'Ofis & Çalışma Alanı Örnek 12', ref: 'TM-OCA-12' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+13', alt: 'Ofis & Çalışma Alanı Örnek 13', ref: 'TM-OCA-13' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+14', alt: 'Ofis & Çalışma Alanı Örnek 14', ref: 'TM-OCA-14' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+15', alt: 'Ofis & Çalışma Alanı Örnek 15', ref: 'TM-OCA-15' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+16', alt: 'Ofis & Çalışma Alanı Örnek 16', ref: 'TM-OCA-16' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+17', alt: 'Ofis & Çalışma Alanı Örnek 17', ref: 'TM-OCA-17' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+18', alt: 'Ofis & Çalışma Alanı Örnek 18', ref: 'TM-OCA-18' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+19', alt: 'Ofis & Çalışma Alanı Örnek 19', ref: 'TM-OCA-19' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+20', alt: 'Ofis & Çalışma Alanı Örnek 20', ref: 'TM-OCA-20' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+21', alt: 'Ofis & Çalışma Alanı Örnek 21', ref: 'TM-OCA-21' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+22', alt: 'Ofis & Çalışma Alanı Örnek 22', ref: 'TM-OCA-22' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+23', alt: 'Ofis & Çalışma Alanı Örnek 23', ref: 'TM-OCA-23' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+24', alt: 'Ofis & Çalışma Alanı Örnek 24', ref: 'TM-OCA-24' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+25', alt: 'Ofis & Çalışma Alanı Örnek 25', ref: 'TM-OCA-25' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+26', alt: 'Ofis & Çalışma Alanı Örnek 26', ref: 'TM-OCA-26' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+27', alt: 'Ofis & Çalışma Alanı Örnek 27', ref: 'TM-OCA-27' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+28', alt: 'Ofis & Çalışma Alanı Örnek 28', ref: 'TM-OCA-28' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+29', alt: 'Ofis & Çalışma Alanı Örnek 29', ref: 'TM-OCA-29' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+30', alt: 'Ofis & Çalışma Alanı Örnek 30', ref: 'TM-OCA-30' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+31', alt: 'Ofis & Çalışma Alanı Örnek 31', ref: 'TM-OCA-31' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+32', alt: 'Ofis & Çalışma Alanı Örnek 32', ref: 'TM-OCA-32' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+33', alt: 'Ofis & Çalışma Alanı Örnek 33', ref: 'TM-OCA-33' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+34', alt: 'Ofis & Çalışma Alanı Örnek 34', ref: 'TM-OCA-34' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+35', alt: 'Ofis & Çalışma Alanı Örnek 35', ref: 'TM-OCA-35' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+36', alt: 'Ofis & Çalışma Alanı Örnek 36', ref: 'TM-OCA-36' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+37', alt: 'Ofis & Çalışma Alanı Örnek 37', ref: 'TM-OCA-37' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+38', alt: 'Ofis & Çalışma Alanı Örnek 38', ref: 'TM-OCA-38' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+39', alt: 'Ofis & Çalışma Alanı Örnek 39', ref: 'TM-OCA-39' },
        { src: 'https://via.placeholder.com/800x600.png?text=Ofis+Alanı+40', alt: 'Ofis & Çalışma Alanı Örnek 40', ref: 'TM-OCA-40' },
      ]
    },
    {
      id: 'magaza-lobi',
      title: 'Mağaza & Lobi',
      images: [
        { src: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=1964&auto=format&fit=crop', alt: 'Bir butik mağaza için tasarlanmış minimalist ve şık ürün sergileme üniteleri', ref: 'TM-ML-01' },
        { src: 'https://images.unsplash.com/photo-1578500523703-832f2814a633?q=80&w=1974&auto=format&fit=crop', alt: 'Bir otel lobisi için üretilmiş, karşılama bankosu ve bekleme alanı mobilyaları', ref: 'TM-ML-02' },
        { src: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=2070&auto=format&fit=crop', alt: 'Minimalist bir perakende mağazasının iç mekanında kullanılan ahşap ve metal detaylar', ref: 'TM-ML-03' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+4', alt: 'Mağaza & Lobi Örnek 4', ref: 'TM-ML-04' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+5', alt: 'Mağaza & Lobi Örnek 5', ref: 'TM-ML-05' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+6', alt: 'Mağaza & Lobi Örnek 6', ref: 'TM-ML-06' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+7', alt: 'Mağaza & Lobi Örnek 7', ref: 'TM-ML-07' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+8', alt: 'Mağaza & Lobi Örnek 8', ref: 'TM-ML-08' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+9', alt: 'Mağaza & Lobi Örnek 9', ref: 'TM-ML-09' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+10', alt: 'Mağaza & Lobi Örnek 10', ref: 'TM-ML-10' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+11', alt: 'Mağaza & Lobi Örnek 11', ref: 'TM-ML-11' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+12', alt: 'Mağaza & Lobi Örnek 12', ref: 'TM-ML-12' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+13', alt: 'Mağaza & Lobi Örnek 13', ref: 'TM-ML-13' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+14', alt: 'Mağaza & Lobi Örnek 14', ref: 'TM-ML-14' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+15', alt: 'Mağaza & Lobi Örnek 15', ref: 'TM-ML-15' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+16', alt: 'Mağaza & Lobi Örnek 16', ref: 'TM-ML-16' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+17', alt: 'Mağaza & Lobi Örnek 17', ref: 'TM-ML-17' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+18', alt: 'Mağaza & Lobi Örnek 18', ref: 'TM-ML-18' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+19', alt: 'Mağaza & Lobi Örnek 19', ref: 'TM-ML-19' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+20', alt: 'Mağaza & Lobi Örnek 20', ref: 'TM-ML-20' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+21', alt: 'Mağaza & Lobi Örnek 21', ref: 'TM-ML-21' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+22', alt: 'Mağaza & Lobi Örnek 22', ref: 'TM-ML-22' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+23', alt: 'Mağaza & Lobi Örnek 23', ref: 'TM-ML-23' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+24', alt: 'Mağaza & Lobi Örnek 24', ref: 'TM-ML-24' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+25', alt: 'Mağaza & Lobi Örnek 25', ref: 'TM-ML-25' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+26', alt: 'Mağaza & Lobi Örnek 26', ref: 'TM-ML-26' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+27', alt: 'Mağaza & Lobi Örnek 27', ref: 'TM-ML-27' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+28', alt: 'Mağaza & Lobi Örnek 28', ref: 'TM-ML-28' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+29', alt: 'Mağaza & Lobi Örnek 29', ref: 'TM-ML-29' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+30', alt: 'Mağaza & Lobi Örnek 30', ref: 'TM-ML-30' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+31', alt: 'Mağaza & Lobi Örnek 31', ref: 'TM-ML-31' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+32', alt: 'Mağaza & Lobi Örnek 32', ref: 'TM-ML-32' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+33', alt: 'Mağaza & Lobi Örnek 33', ref: 'TM-ML-33' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+34', alt: 'Mağaza & Lobi Örnek 34', ref: 'TM-ML-34' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+35', alt: 'Mağaza & Lobi Örnek 35', ref: 'TM-ML-35' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+36', alt: 'Mağaza & Lobi Örnek 36', ref: 'TM-ML-36' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+37', alt: 'Mağaza & Lobi Örnek 37', ref: 'TM-ML-37' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+38', alt: 'Mağaza & Lobi Örnek 38', ref: 'TM-ML-38' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+39', alt: 'Mağaza & Lobi Örnek 39', ref: 'TM-ML-39' },
        { src: 'https://via.placeholder.com/800x600.png?text=Mağaza+Lobi+40', alt: 'Mağaza & Lobi Örnek 40', ref: 'TM-ML-40' },
      ]
    }
  ]
};