export const tvUniteleriData = {
  title: "TV Üniteleri & Yaşam Alanları",
  category: "Salon Mobilyaları",
  coverImage: "https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/5.png?updatedAt=1755891413231",
  galleryDescription: "Salonunuzun odak noktası olacak, modern ve fonksiyonel TV üniteleri tasarlıyoruz. Kitaplık, raf ve depolama çözümleriyle yaşam alanınızı tamamlıyoruz.",
  sections: [
     {
      id: 'duvar-uniteleri',
      title: 'Duvar Üniteleri & Kitaplıklar',
      images: [
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/8.png?updatedAt=1755891413590', alt: 'Modern duvara monte TV ünitesi ve kitaplık sistemi', ref: 'TV-DU-01' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/7.png?updatedAt=1755891413455', alt: 'Asimetrik raflı, ceviz TV ünitesi ve duvar dekorasyonu', ref: 'TV-DU-02' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/9.png?updatedAt=1755891413220', alt: 'Minimalist TV duvarı, gizli dolaplı ve LED aydınlatmalı', ref: 'TV-DU-03' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/31.png?updatedAt=1755891413112', alt: 'Geniş kitaplıklı, ahşap TV ünitesi tasarımı', ref: 'TV-DU-04' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/6.png?updatedAt=1755891413049', alt: 'Endüstriyel tarzda metal ve ahşap TV ünitesi ve raf sistemi', ref: 'TV-DU-05' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/4.png?updatedAt=1755891413035', alt: 'Şömineli, modern TV duvarı ve entegre dolaplar', ref: 'TV-DU-06' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/29.png?updatedAt=1755891411325', alt: 'Beyaz lake ve ahşap kombinasyonlu TV duvar ünitesi', ref: 'TV-DU-07' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/30.png?updatedAt=1755891411221', alt: 'Rustik tarzda, masif ahşap TV ünitesi ve duvar paneli', ref: 'TV-DU-08' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/3.png?updatedAt=1755891410650', alt: 'Mermer detaylı, lüks TV duvarı tasarımı', ref: 'TV-DU-09' },
        { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/28.png?updatedAt=1755891409129', alt: 'Koyu renk ahşap kaplamalı, modern ve şık TV ünitesi', ref: 'TV-DU-10' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+11', alt: 'Duvar Ünitesi & Kitaplık Örnek 11', ref: 'TV-DU-11' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+12', alt: 'Duvar Ünitesi & Kitaplık Örnek 12', ref: 'TV-DU-12' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+13', alt: 'Duvar Ünitesi & Kitaplık Örnek 13', ref: 'TV-DU-13' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+14', alt: 'Duvar Ünitesi & Kitaplık Örnek 14', ref: 'TV-DU-14' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+15', alt: 'Duvar Ünitesi & Kitaplık Örnek 15', ref: 'TV-DU-15' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+16', alt: 'Duvar Ünitesi & Kitaplık Örnek 16', ref: 'TV-DU-16' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+17', alt: 'Duvar Ünitesi & Kitaplık Örnek 17', ref: 'TV-DU-17' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+18', alt: 'Duvar Ünitesi & Kitaplık Örnek 18', ref: 'TV-DU-18' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+19', alt: 'Duvar Ünitesi & Kitaplık Örnek 19', ref: 'TV-DU-19' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+20', alt: 'Duvar Ünitesi & Kitaplık Örnek 20', ref: 'TV-DU-20' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+21', alt: 'Duvar Ünitesi & Kitaplık Örnek 21', ref: 'TV-DU-21' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+22', alt: 'Duvar Ünitesi & Kitaplık Örnek 22', ref: 'TV-DU-22' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+23', alt: 'Duvar Ünitesi & Kitaplık Örnek 23', ref: 'TV-DU-23' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+24', alt: 'Duvar Ünitesi & Kitaplık Örnek 24', ref: 'TV-DU-24' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+25', alt: 'Duvar Ünitesi & Kitaplık Örnek 25', ref: 'TV-DU-25' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+26', alt: 'Duvar Ünitesi & Kitaplık Örnek 26', ref: 'TV-DU-26' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+27', alt: 'Duvar Ünitesi & Kitaplık Örnek 27', ref: 'TV-DU-27' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+28', alt: 'Duvar Ünitesi & Kitaplık Örnek 28', ref: 'TV-DU-28' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+29', alt: 'Duvar Ünitesi & Kitaplık Örnek 29', ref: 'TV-DU-29' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+30', alt: 'Duvar Ünitesi & Kitaplık Örnek 30', ref: 'TV-DU-30' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+31', alt: 'Duvar Ünitesi & Kitaplık Örnek 31', ref: 'TV-DU-31' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+32', alt: 'Duvar Ünitesi & Kitaplık Örnek 32', ref: 'TV-DU-32' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+33', alt: 'Duvar Ünitesi & Kitaplık Örnek 33', ref: 'TV-DU-33' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+34', alt: 'Duvar Ünitesi & Kitaplık Örnek 34', ref: 'TV-DU-34' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+35', alt: 'Duvar Ünitesi & Kitaplık Örnek 35', ref: 'TV-DU-35' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+36', alt: 'Duvar Ünitesi & Kitaplık Örnek 36', ref: 'TV-DU-36' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+37', alt: 'Duvar Ünitesi & Kitaplık Örnek 37', ref: 'TV-DU-37' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+38', alt: 'Duvar Ünitesi & Kitaplık Örnek 38', ref: 'TV-DU-38' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+39', alt: 'Duvar Ünitesi & Kitaplık Örnek 39', ref: 'TV-DU-39' },
        { src: 'https://via.placeholder.com/800x600.png?text=Duvar+Ünitesi+40', alt: 'Duvar Ünitesi & Kitaplık Örnek 40', ref: 'TV-DU-40' },
      ]
     },
     {
       id: 'konsol-uniteler',
       title: 'Konsol Tipi Üniteler',
       images: [
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/2.png?updatedAt=1755891408948', alt: 'İskandinav tarzı, meşe ahşap TV sehpası', ref: 'TV-KU-01' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/20.png?updatedAt=1755891408865', alt: 'Retro tasarımlı, ceviz TV konsolu', ref: 'TV-KU-02' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/23.png?updatedAt=1755891408854', alt: 'Metal ayaklı, minimalist TV sehpası', ref: 'TV-KU-03' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/21.png?updatedAt=1755891408851', alt: 'Lake boyalı, modern TV konsolu', ref: 'TV-KU-04' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/25.png?updatedAt=1755891408615', alt: 'Masif ahşaptan, el işçiliği TV ünitesi', ref: 'TV-KU-05' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/22.png?updatedAt=1755891408597', alt: 'Çekmeceli ve dolaplı, fonksiyonel TV sehpası', ref: 'TV-KU-06' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/27.png?updatedAt=1755891408382', alt: 'Cam detaylı, şık TV konsolu', ref: 'TV-KU-07' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/24.png?updatedAt=1755891407991', alt: 'Country tarzı, eskitme görünümlü TV ünitesi', ref: 'TV-KU-08' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/26.png?updatedAt=1755891407737', alt: 'Açık raflı, sade TV sehpası', ref: 'TV-KU-09' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/19.png?updatedAt=1755891406258', alt: 'Geniş ve alçak tasarımlı modern TV konsolu', ref: 'TV-KU-10' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+11', alt: 'Konsol Tipi Ünite Örnek 11', ref: 'TV-KU-11' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+12', alt: 'Konsol Tipi Ünite Örnek 12', ref: 'TV-KU-12' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+13', alt: 'Konsol Tipi Ünite Örnek 13', ref: 'TV-KU-13' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+14', alt: 'Konsol Tipi Ünite Örnek 14', ref: 'TV-KU-14' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+15', alt: 'Konsol Tipi Ünite Örnek 15', ref: 'TV-KU-15' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+16', alt: 'Konsol Tipi Ünite Örnek 16', ref: 'TV-KU-16' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+17', alt: 'Konsol Tipi Ünite Örnek 17', ref: 'TV-KU-17' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+18', alt: 'Konsol Tipi Ünite Örnek 18', ref: 'TV-KU-18' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+19', alt: 'Konsol Tipi Ünite Örnek 19', ref: 'TV-KU-19' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+20', alt: 'Konsol Tipi Ünite Örnek 20', ref: 'TV-KU-20' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+21', alt: 'Konsol Tipi Ünite Örnek 21', ref: 'TV-KU-21' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+22', alt: 'Konsol Tipi Ünite Örnek 22', ref: 'TV-KU-22' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+23', alt: 'Konsol Tipi Ünite Örnek 23', ref: 'TV-KU-23' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+24', alt: 'Konsol Tipi Ünite Örnek 24', ref: 'TV-KU-24' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+25', alt: 'Konsol Tipi Ünite Örnek 25', ref: 'TV-KU-25' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+26', alt: 'Konsol Tipi Ünite Örnek 26', ref: 'TV-KU-26' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+27', alt: 'Konsol Tipi Ünite Örnek 27', ref: 'TV-KU-27' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+28', alt: 'Konsol Tipi Ünite Örnek 28', ref: 'TV-KU-28' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+29', alt: 'Konsol Tipi Ünite Örnek 29', ref: 'TV-KU-29' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+30', alt: 'Konsol Tipi Ünite Örnek 30', ref: 'TV-KU-30' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+31', alt: 'Konsol Tipi Ünite Örnek 31', ref: 'TV-KU-31' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+32', alt: 'Konsol Tipi Ünite Örnek 32', ref: 'TV-KU-32' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+33', alt: 'Konsol Tipi Ünite Örnek 33', ref: 'TV-KU-33' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+34', alt: 'Konsol Tipi Ünite Örnek 34', ref: 'TV-KU-34' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+35', alt: 'Konsol Tipi Ünite Örnek 35', ref: 'TV-KU-35' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+36', alt: 'Konsol Tipi Ünite Örnek 36', ref: 'TV-KU-36' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+37', alt: 'Konsol Tipi Ünite Örnek 37', ref: 'TV-KU-37' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+38', alt: 'Konsol Tipi Ünite Örnek 38', ref: 'TV-KU-38' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+39', alt: 'Konsol Tipi Ünite Örnek 39', ref: 'TV-KU-39' },
          { src: 'https://via.placeholder.com/800x600.png?text=Konsol+Ünite+40', alt: 'Konsol Tipi Ünite Örnek 40', ref: 'TV-KU-40' },
       ]
     },
     {
       id: 'ozel-tasarimlar',
       title: 'Özel Tasarımlar',
       images: [
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/11.png?updatedAt=1755891403865', alt: 'Projeksiyon perdesi entegreli özel TV duvarı', ref: 'TV-OT-01' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/13.png?updatedAt=1755891403845', alt: 'Döner mekanizmalı, odanın her yerinden izlenebilen TV ünitesi', ref: 'TV-OT-02' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/1.png?updatedAt=1755891403841', alt: 'Akustik panel kaplamalı, ses sistemi entegre TV duvarı', ref: 'TV-OT-03' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/14.png?updatedAt=1755891403819', alt: 'Gizli bar bölmeli, özel tasarım TV ünitesi', ref: 'TV-OT-04' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/10.png?updatedAt=1755891403815', alt: 'Heykelsi formda, sanatsal TV ünitesi tasarımı', ref: 'TV-OT-05' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/12.png?updatedAt=1755891403761', alt: 'Çalışma masası ile birleştirilmiş fonksiyonel TV ünitesi', ref: 'TV-OT-06' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/15.png?updatedAt=1755891403668', alt: 'Kavisli ve organik formlarda tasarlanmış TV duvarı', ref: 'TV-OT-07' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/18.png?updatedAt=1755891403615', alt: 'Oda bölücü olarak kullanılan çift taraflı TV ünitesi', ref: 'TV-OT-08' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/16.png?updatedAt=1755891403403', alt: 'Tavandan asmalı, modern ve sıradışı TV ünitesi', ref: 'TV-OT-09' },
          { src: 'https://ik.imagekit.io/Aifct1/mutfak/tv%20%C3%BCnitesi/17.png?updatedAt=1755891403260', alt: 'Işık ve gölge oyunları ile tasarlanmış dekoratif TV duvarı', ref: 'TV-OT-10' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+11', alt: 'Özel Tasarım TV Ünitesi Örnek 11', ref: 'TV-OT-11' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+12', alt: 'Özel Tasarım TV Ünitesi Örnek 12', ref: 'TV-OT-12' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+13', alt: 'Özel Tasarım TV Ünitesi Örnek 13', ref: 'TV-OT-13' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+14', alt: 'Özel Tasarım TV Ünitesi Örnek 14', ref: 'TV-OT-14' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+15', alt: 'Özel Tasarım TV Ünitesi Örnek 15', ref: 'TV-OT-15' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+16', alt: 'Özel Tasarım TV Ünitesi Örnek 16', ref: 'TV-OT-16' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+17', alt: 'Özel Tasarım TV Ünitesi Örnek 17', ref: 'TV-OT-17' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+18', alt: 'Özel Tasarım TV Ünitesi Örnek 18', ref: 'TV-OT-18' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+19', alt: 'Özel Tasarım TV Ünitesi Örnek 19', ref: 'TV-OT-19' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+20', alt: 'Özel Tasarım TV Ünitesi Örnek 20', ref: 'TV-OT-20' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+21', alt: 'Özel Tasarım TV Ünitesi Örnek 21', ref: 'TV-OT-21' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+22', alt: 'Özel Tasarım TV Ünitesi Örnek 22', ref: 'TV-OT-22' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+23', alt: 'Özel Tasarım TV Ünitesi Örnek 23', ref: 'TV-OT-23' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+24', alt: 'Özel Tasarım TV Ünitesi Örnek 24', ref: 'TV-OT-24' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+25', alt: 'Özel Tasarım TV Ünitesi Örnek 25', ref: 'TV-OT-25' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+26', alt: 'Özel Tasarım TV Ünitesi Örnek 26', ref: 'TV-OT-26' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+27', alt: 'Özel Tasarım TV Ünitesi Örnek 27', ref: 'TV-OT-27' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+28', alt: 'Özel Tasarım TV Ünitesi Örnek 28', ref: 'TV-OT-28' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+29', alt: 'Özel Tasarım TV Ünitesi Örnek 29', ref: 'TV-OT-29' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+30', alt: 'Özel Tasarım TV Ünitesi Örnek 30', ref: 'TV-OT-30' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+31', alt: 'Özel Tasarım TV Ünitesi Örnek 31', ref: 'TV-OT-31' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+32', alt: 'Özel Tasarım TV Ünitesi Örnek 32', ref: 'TV-OT-32' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+33', alt: 'Özel Tasarım TV Ünitesi Örnek 33', ref: 'TV-OT-33' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+34', alt: 'Özel Tasarım TV Ünitesi Örnek 34', ref: 'TV-OT-34' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+35', alt: 'Özel Tasarım TV Ünitesi Örnek 35', ref: 'TV-OT-35' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+36', alt: 'Özel Tasarım TV Ünitesi Örnek 36', ref: 'TV-OT-36' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+37', alt: 'Özel Tasarım TV Ünitesi Örnek 37', ref: 'TV-OT-37' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+38', alt: 'Özel Tasarım TV Ünitesi Örnek 38', ref: 'TV-OT-38' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+39', alt: 'Özel Tasarım TV Ünitesi Örnek 39', ref: 'TV-OT-39' },
          { src: 'https://via.placeholder.com/800x600.png?text=Özel+Tasarım+40', alt: 'Özel Tasarım TV Ünitesi Örnek 40', ref: 'TV-OT-40' },
       ]
     }
  ]
};